export const SET_ALERT = 'SET_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const SET_TOAST = 'SET_TOAST';
export const CLEAR_TOAST = 'CLEAR_TOAST';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const LOADING_PRODUCTS = 'LOADING_PRODUCTS';
export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';

export const ADD_PRODUCT_DETAILS = 'ADD_PRODUCT_DETAILS';
export const LOADING_PRODUCT_DETAILS = 'LOADING_PRODUCT_DETAILS';
export const CLEAR_PRODUCT_DETAILS = 'CLEAR_PRODUCT_DETAILS';
export const FETCH_PRODUCT_DETAILS_ERROR = 'FETCH_PRODUCT_DETAILS_ERROR';

export const ADD_CART_ID = 'ADD_CART_ID';
export const ADD_CART_ITEMS = 'ADD_CART_ITEMS';
export const LOADING_CART_ITEMS = 'LOADING_CART_ITEMS';
export const CLEAR_CART_ITEMS = 'CLEAR_CART_ITEMS';
export const FETCH_CART_ITEMS_ERROR = 'FETCH_CART_ITEMS_ERROR';

export const ADD_FAVOURITES = 'ADD_FAVOURITES';
export const LOADING_FAVOURITES = 'LOADING_FAVOURITES';
export const CLEAR_FAVOURITES = 'CLEAR_FAVOURITES';
export const FETCH_FAVOURITES_ERROR = 'FETCH_FAVOURITES_ERROR';

export const ADD_PROFILE = 'ADD_PROFILE';
export const LOADING_PROFILE = 'LOADING_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const FETCH_PROFILE_ERROR = 'FETCH_PROFILE_ERROR';

export const ADD_PURCHASES = 'ADD_PURCHASES';
export const LOADING_PURCHASES = 'LOADING_PURCHASES';
export const CLEAR_PURCHASES = 'CLEAR_PURCHASES';
export const FETCH_PURCHASES_ERROR = 'FETCH_PURCHASES_ERROR';